name: Docker build

concurrency: 
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted,Linux,ARM64]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/severnt/acme-dns:${{ github.ref }}
            ghcr.io/severnt/acme-dns:latest

